cliente.println("<html>");
cliente.println("<!DOCTYPE html>");
cliente.println("<head>");
cliente.println("	<meta charset='utf-8' />");
cliente.println("	<title>CSS3 Buttons</title>");
cliente.println("    <META NAME='ROBOTS' CONTENT='NOINDEX, NOFOLLOW'>");
cliente.println("	<link rel='stylesheet' href='style2.css'>");
cliente.println("	<script type='text/javascript' src='js/jquery-1.7.2.min.js'></script>");
cliente.println("	<script type='text/javascript'>");
cliente.println("		$(document).ready(function(){");
cliente.println("			$("#button').on("click', function(){");
cliente.println("				$(this).toggleClass("on");");
cliente.println("			});");
cliente.println("		});");
cliente.println("	</script>");
cliente.println("</head>");
cliente.println("<body>");
cliente.println("	<section>");
cliente.println("		<a href='#' id='button'>&#xF011;</a>");
cliente.println("		<span></span>");
cliente.println("	</section>");
cliente.println("</body>");
cliente.println("</html>");
